# Generated by Django 6.0.2 on 2026-02-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.PositiveSmallIntegerField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('npc', models.CharField(blank=True, help_text='NPC who gives/completes the quest', max_length=200)),
                ('primary_zone', models.CharField(blank=True, max_length=200)),
                ('zones_json', models.JSONField(blank=True, default=list, help_text='List of zone names involved in the quest')),
                ('hint_text', models.TextField(blank=True, help_text='Rough location / gameplay hint')),
                ('is_required', models.BooleanField(default=False, help_text='Required for campaign progression')),
                ('gives_passive_point', models.BooleanField(db_index=True, default=False)),
                ('passive_points', models.PositiveSmallIntegerField(default=0, help_text='Number of passive skill points granted')),
                ('gives_refund_points', models.BooleanField(db_index=True, default=False)),
                ('refund_points', models.PositiveSmallIntegerField(default=0, help_text='Number of refund/respec points granted')),
                ('gives_other', models.BooleanField(default=False, help_text='Grants non-point rewards (gems, items, etc.)')),
                ('other_reward_text', models.CharField(blank=True, max_length=300)),
                ('is_pinned_default', models.BooleanField(default=False, help_text='Pinned by default in the quest list')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['act', 'sort_order', 'name'],
            },
        ),
    ]
